swagger: '2.0'
info:
  title: Sourcebans API
  description: This is a simple API allowing show, add and modify bans.
  version: "1.0.0"
# the domain of the service
host: polls.apiblueprint.org
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths

produces:
  - application/json
paths:
  /bans:
    get:
      summary: Запросить бан
      description: |
        Получить информацию о банах.
      parameters:
        - name: offset
          in: query
          description: Смещение
          required: true
          type: number
          format: double
        - name: limit
          in: query
          description: Количество банов
          required: true
          type: number
          format: double

      responses:
        200:
          description: Array of bans
          schema:
            type: array
            items:
                $ref: '#/definitions/Bans'

definitions:
  Bans:
    type: object
    properties:
      created_at:
        type: number
        description: Время, когда игрока забанили.
      player_steamid32:
        type: string
        description: SteamID игрока.
      admin_steamid32:
        type: string
        description: SteamID админа.
      reason:
        type: string
        description: Причина бана
      expires:
        type: number
        description: Время окончания бана. 0 - Никогда .